// BedWars kit dataset — compiled from the BedWars Fandom Wiki (Kit page + Class page)
// class: Fighter, Ranged, Tank, Support, Movement, Economy, Destroyer, Defender, Misc
// obtain: Free, Shop, BattlePass, PlayerLevel, Bundle

const KITS = [
  // Free (instant on join)
  { name: "Isabel", class: "Fighter", obtain: "Free", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/7e/Isabel.png/revision/latest?cb=20250407054845" },
  { name: "Ragnar", class: "Destroyer", obtain: "Free", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/7c/Ragnar.png/revision/latest?cb=20260509200230" },
  { name: "Marcel", class: "Defender", obtain: "Free", img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/25/Marcel.png/revision/latest?cb=20251207162601" },

  // Player Level milestones
  { name: "Whisper", class: "Support", obtain: "PlayerLevel", level: 10, img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/44/Whisper.png/revision/latest?cb=20230407134322" },
  { name: "Taliyah", class: "Economy", obtain: "PlayerLevel", level: 15, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b8/Taliyah.png/revision/latest?cb=20230715125806" },

  // Shop kits (399/10,000 or 479/12,000)
  { name: "Abaddon", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/0/0c/Abaddon.png/revision/latest?cb=20250628003514" },
  { name: "Adetunde", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/73/Adetunde.png/revision/latest?cb=20221227124206" },
  { name: "Arachne", class: "Movement", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/e/e0/Arachne.png/revision/latest?cb=20241019124551" },
  { name: "Archer", class: "Ranged", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/29/Archer.png/revision/latest?cb=20220406150805" },
  { name: "Axolotl Amy", class: "Support", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/97/Axolotl_Amy.png/revision/latest?cb=20220406150803" },
  { name: "Baker", class: "Support", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/d/d0/Baker.png/revision/latest?cb=20250227044023" },
  { name: "Barbarian", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b6/Barbarian.png/revision/latest?cb=20250227044003" },
  { name: "Builder", class: "Defender", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/14/Builder.png/revision/latest?cb=20220406213444" },
  { name: "Crypt", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/77/Crypt_%28kit%29.png/revision/latest?cb=20221029101653" },
  { name: "Cyber", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/c/cd/Cyber.png/revision/latest?cb=20220430181556" },
  { name: "Death Adder", class: "Destroyer", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/8/82/Death_Adder.png/revision/latest?cb=20240903141945" },
  { name: "Eldertree", class: "Tank", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/bd/Eldertree.png/revision/latest?cb=20220406213944" },
  { name: "Eldric", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b2/Eldric.png/revision/latest?cb=20240410143751" },
  { name: "Evelynn", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/ab/Evelynn.png/revision/latest?cb=20250304061427" },
  { name: "Farmer Cletus", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/28/Farmer_Cletus.png/revision/latest?cb=20250227062041" },
  { name: "Freiya", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/ac/Freiya.png/revision/latest?cb=20220406213851" },
  { name: "Grim Reaper", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/74/Grim_Reaper.png/revision/latest?cb=20250304061422" },
  { name: "Grove", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/18/Grove.png/revision/latest?cb=20241214101745" },
  { name: "Hannah", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/0/0d/Hannah.png/revision/latest?cb=20250227044704" },
  { name: "Infernal Shielder", class: "Tank", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/d/d4/Infernal_Shielder.png/revision/latest?cb=20220327010153" },
  { name: "Kaida", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/3/34/Kaida.png/revision/latest?cb=20240903141709" },
  { name: "Lassy", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/3/3f/Lassy.png/revision/latest?cb=20220406153250" },
  { name: "Lian", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/e/e4/Lian.png/revision/latest?cb=20251025053117" },
  { name: "Lyla", class: "Ranged", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/4c/Lyla.png/revision/latest?cb=20250227044214" },
  { name: "Marina", class: "Defender", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/9d/Marina.png/revision/latest?cb=20240622022939" },
  { name: "Marrow", class: "Misc", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/6/6a/Marrow.png/revision/latest?cb=20251029233344" },
  { name: "Martin", class: "Tank", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/d/d8/Martin.png/revision/latest?cb=20250418231740" },
  { name: "Melody", class: "Support", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/98/Melody.png/revision/latest?cb=20220401221132" },
  { name: "Milo", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/5c/Milo.png/revision/latest?cb=20240319165120" },
  { name: "Miner", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/4a/Miner.png/revision/latest?cb=20220406214735" },
  { name: "Nahla", class: "Support", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/58/Nahla.png/revision/latest?cb=20250418231842" },
  { name: "Nazar", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/16/Nazar.png/revision/latest?cb=20240903141857" },
  { name: "Pirate Davey", class: "Destroyer", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/2c/Pirate_Davey.png/revision/latest?cb=20220401223429" },
  { name: "Ramil", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f8/Ramil.png/revision/latest?cb=20250418231926" },
  { name: "Silas", class: "Support", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/a6/Silas.png/revision/latest?cb=20240903141835" },
  { name: "Skoll", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/15/Skoll.png/revision/latest?cb=20250227044241" },
  { name: "Trinity", class: "Support", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/9c/Trinity.png/revision/latest?cb=20220928151708" },
  { name: "Triton", class: "Movement", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/5d/Triton.png/revision/latest?cb=20240628223010" },
  { name: "Trixie", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/92/Trixie.png/revision/latest?cb=20250301040101" },
  { name: "Uma", class: "Ranged", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/45/Uma.png/revision/latest?cb=20241214101810" },
  { name: "Vanessa", class: "Ranged", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/a0/Vanessa.png/revision/latest?cb=20250227044034" },
  { name: "Void Knight", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/aa/Void_Knight.png/revision/latest?cb=20250227044626" },
  { name: "Vulcan", class: "Defender", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/d/df/Vulcan.png/revision/latest?cb=20220322230037" },
  { name: "Wren", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b0/Wren.png/revision/latest?cb=20240903141755" },
  { name: "Yuzi", class: "Movement", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/77/Yuzi.png/revision/latest?cb=20250304061457" },
  { name: "Zarrah", class: "Fighter", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/fd/Zarrah.png/revision/latest?cb=20260210005044" },
  { name: "Zenith", class: "Economy", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/6/66/Zenith.png/revision/latest?cb=20221119120919" },
  { name: "Zeno", class: "Ranged", obtain: "Shop", img: "https://static.wikia.nocookie.net/robloxbedwars/images/c/c1/Zeno.png/revision/latest?cb=20231205211444" },

  // Bundle-exclusive kits (holiday / lunar / event bundles, not in general shop)
  { name: "Void Regent", class: "Movement", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/6/66/Void_Regent.png/revision/latest?cb=20250131011341" },
  { name: "Sheila", class: "Fighter", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/54/Sheila.png/revision/latest?cb=20221227123624" },
  { name: "Sigrid", class: "Movement", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/73/Sigrid.png/revision/latest?cb=20231231163347" },
  { name: "Krystal", class: "Movement", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/4d/Krystal.png/revision/latest?cb=20241224040038" },
  { name: "Sophia", class: "Misc", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/1e/Sophia.png/revision/latest?cb=20251220122847" },
  { name: "Ember", class: "Fighter", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/0/06/Ember_%28kit%29.png/revision/latest?cb=20220520140250" },
  { name: "Lumen", class: "Fighter", obtain: "Bundle", img: "https://static.wikia.nocookie.net/robloxbedwars/images/6/6c/Lumen.png/revision/latest?cb=20220520140315" },

  // Battle Pass kits (various seasons)
  { name: "Warrior", class: "Tank", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/97/Warrior.png/revision/latest?cb=20220406153245" },
  { name: "Bounty Hunter", class: "Economy", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/1d/Bounty_Hunter.png/revision/latest?cb=20220406153243" },
  { name: "Beekeeper Beatrix", class: "Economy", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/4c/Beekeeper_Beatrix.png/revision/latest?cb=20250227044203" },
  { name: "Jade", class: "Movement", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/7e/Jade.png/revision/latest?cb=20220720154621" },
  { name: "Raven", class: "Ranged", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/5e/Raven_%28kit%29.png/revision/latest?cb=20220406153249" },
  { name: "Spirit Catcher", class: "Ranged", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/a5/Spirit_Catcher.png/revision/latest?cb=20220406153241" },
  { name: "Pyro", class: "Fighter", obtain: "BattlePass", season: 1, img: "https://static.wikia.nocookie.net/robloxbedwars/images/c/c8/Pyro.png/revision/latest?cb=20220406153240" },
  { name: "Trapper", class: "Defender", obtain: "BattlePass", season: 2, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b8/Trapper.png/revision/latest?cb=20220406153238" },
  { name: "Gompy", class: "Ranged", obtain: "BattlePass", season: 2, img: "https://static.wikia.nocookie.net/robloxbedwars/images/c/ce/Gompy.png/revision/latest?cb=20220720154630" },
  { name: "Fisherman", class: "Economy", obtain: "BattlePass", season: 2, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f0/Fisherman.png/revision/latest?cb=20220406153235" },
  { name: "Jack", class: "Ranged", obtain: "BattlePass", season: 2, img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/46/Jack.png/revision/latest?cb=20220406153232" },
  { name: "Ares", class: "Ranged", obtain: "BattlePass", season: 2, img: "https://static.wikia.nocookie.net/robloxbedwars/images/0/05/Ares.png/revision/latest?cb=20220406153230" },
  { name: "Santa", class: "Destroyer", obtain: "BattlePass", season: 3, img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/5b/Santa.png/revision/latest?cb=20220406153223" },
  { name: "Gingerbread Man", class: "Support", obtain: "BattlePass", season: 3, img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/2e/Gingerbread_Man.png/revision/latest?cb=20220406153225" },
  { name: "Smoke", class: "Destroyer", obtain: "BattlePass", season: 3, img: "https://static.wikia.nocookie.net/robloxbedwars/images/c/c6/Smoke.png/revision/latest?cb=20220406153220" },
  { name: "Yeti", class: "Destroyer", obtain: "BattlePass", season: 3, img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/7d/Yeti.png/revision/latest?cb=20220406153226" },
  { name: "Frosty", class: "Ranged", obtain: "BattlePass", season: 3, img: "https://static.wikia.nocookie.net/robloxbedwars/images/3/3d/Frosty.png/revision/latest?cb=20220406153222" },
  { name: "Aery", class: "Fighter", obtain: "BattlePass", season: 3, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f8/Aery.png/revision/latest?cb=20220406153228" },
  { name: "Metal Detector", class: "Economy", obtain: "BattlePass", season: 4, img: "https://static.wikia.nocookie.net/robloxbedwars/images/3/35/Metal_Detector.png/revision/latest?cb=20220415220556" },
  { name: "Alchemist", class: "Support", obtain: "BattlePass", season: 4, img: "https://static.wikia.nocookie.net/robloxbedwars/images/5/5b/Alchemist.png/revision/latest?cb=20220406150801" },
  { name: "Sheep Herder", class: "Fighter", obtain: "BattlePass", season: 4, img: "https://static.wikia.nocookie.net/robloxbedwars/images/d/da/Sheep_Herder.png/revision/latest?cb=20220406153218" },
  { name: "Crocowolf", class: "Fighter", obtain: "BattlePass", season: 4, img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/27/Crocowolf.png/revision/latest?cb=20220406153216" },
  { name: "Conqueror", class: "Support", obtain: "BattlePass", season: 4, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/bb/Conqueror.png/revision/latest?cb=20220507184604" },
  { name: "Nyx", class: "Fighter", obtain: "BattlePass", season: 4, img: "https://static.wikia.nocookie.net/robloxbedwars/images/8/8e/Nyx.png/revision/latest?cb=20220406155112" },
  { name: "Lucía", class: "Economy", obtain: "BattlePass", season: 5, img: "https://static.wikia.nocookie.net/robloxbedwars/images/8/82/Luc%C3%ADa.png/revision/latest?cb=20220624230639" },
  { name: "Merchant Marco", class: "Economy", obtain: "BattlePass", season: 5, img: "https://static.wikia.nocookie.net/robloxbedwars/images/6/62/Merchant_Marco.png/revision/latest?cb=20220611034914" },
  { name: "Dino Tamer Dom", class: "Destroyer", obtain: "BattlePass", season: 5, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/fe/Dino_Tamer_Dom.png/revision/latest?cb=20220611034921" },
  { name: "Cobalt", class: "Tank", obtain: "BattlePass", season: 5, img: "https://static.wikia.nocookie.net/robloxbedwars/images/8/80/Cobalt.png/revision/latest?cb=20220709092545" },
  { name: "Star Collector Stella", class: "Support", obtain: "BattlePass", season: 5, img: "https://static.wikia.nocookie.net/robloxbedwars/images/e/ec/Star_Collector_Stella.png/revision/latest?cb=20220611034908" },
  { name: "Zephyr", class: "Movement", obtain: "BattlePass", season: 5, img: "https://static.wikia.nocookie.net/robloxbedwars/images/3/3e/Zephyr.png/revision/latest?cb=20220611034753" },
  { name: "Lani", class: "Support", obtain: "BattlePass", season: 6, img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/7a/Lani.png/revision/latest?cb=20221008110422" },
  { name: "Whim", class: "Fighter", obtain: "BattlePass", season: 6, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f7/Whim.png/revision/latest?cb=20251214035107" },
  { name: "Xu'rot", class: "Fighter", obtain: "BattlePass", season: 6, img: "https://static.wikia.nocookie.net/robloxbedwars/images/4/4b/Xu%27rot.png/revision/latest?cb=20220924095536" },
  { name: "Warden", class: "Destroyer", obtain: "BattlePass", season: 6, img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/a5/Warden.png/revision/latest?cb=20221127152556" },
  { name: "Kaliyah", class: "Fighter", obtain: "BattlePass", season: 6, img: "https://static.wikia.nocookie.net/robloxbedwars/images/c/c1/Kaliyah.png/revision/latest?cb=20220924095538" },
  { name: "Drill", class: "Economy", obtain: "BattlePass", season: 7, img: "https://static.wikia.nocookie.net/robloxbedwars/images/8/88/Drill.png/revision/latest?cb=20230402200402" },
  { name: "Flora", class: "Movement", obtain: "BattlePass", season: 7, img: "https://static.wikia.nocookie.net/robloxbedwars/images/9/90/Flora.png/revision/latest?cb=20230715150529" },
  { name: "Umbra", class: "Support", obtain: "BattlePass", season: 7, img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/a2/Umbra.png/revision/latest?cb=20230407134845" },
  { name: "Caitlyn", class: "Fighter", obtain: "BattlePass", season: 7, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f4/Caitlyn.png/revision/latest?cb=20230407134938" },
  { name: "Ignis", class: "Support", obtain: "BattlePass", season: 8, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/bf/Ignis.png/revision/latest?cb=20230715150959" },
  { name: "Fortuna", class: "Fighter", obtain: "BattlePass", season: 8, img: "https://static.wikia.nocookie.net/robloxbedwars/images/1/14/Fortuna.png/revision/latest?cb=20230715151111" },
  { name: "Elektra", class: "Movement", obtain: "BattlePass", season: 8, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b4/Elektra.png/revision/latest?cb=20230715151028" },
  { name: "Umeko", class: "Ranged", obtain: "BattlePass", season: 9, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b2/Umeko.png/revision/latest?cb=20231205205436" },
  { name: "Yamini", class: "Movement", obtain: "BattlePass", season: 9, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b5/Yamini.png/revision/latest?cb=20231116122229" },
  { name: "Cogsworth", class: "Economy", obtain: "BattlePass", season: 9, img: "https://static.wikia.nocookie.net/robloxbedwars/images/a/a8/Cogsworth.png/revision/latest?cb=20231117225130" },
  { name: "Noelle", class: "Support", obtain: "BattlePass", season: 9, img: "https://static.wikia.nocookie.net/robloxbedwars/images/b/b0/Noelle.png/revision/latest?cb=20231205211339" },
  { name: "Terra", class: "Fighter", obtain: "BattlePass", season: 9, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f5/Terra.png/revision/latest?cb=20231117124457" },
  { name: "Agni", class: "Fighter", obtain: "BattlePass", season: 10, img: "https://static.wikia.nocookie.net/robloxbedwars/images/3/35/Agni.png/revision/latest?cb=20240405204638" },
  { name: "Styx", class: "Movement", obtain: "BattlePass", season: 10, img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/75/Styx.png/revision/latest?cb=20240413185806" },
  { name: "Nyoka", class: "Support", obtain: "BattlePass", season: 10, img: "https://static.wikia.nocookie.net/robloxbedwars/images/7/79/Nyoka.png/revision/latest?cb=20240405204605" },
  { name: "Bekzat", class: "Ranged", obtain: "BattlePass", season: 10, img: "https://static.wikia.nocookie.net/robloxbedwars/images/f/f4/Bekzat.png/revision/latest?cb=20240405204457" },
  { name: "Hephaestus", class: "Tank", obtain: "BattlePass", season: 10, img: "https://static.wikia.nocookie.net/robloxbedwars/images/2/25/Hephaestus.png/revision/latest?cb=20250304061634" },
  { name: "Zola", class: "Support", obtain: "BattlePass", season: 11, img: "https://static.wikia.nocookie.net/robloxbedwars/images/d/d4/Zola.png/revision/latest?cb=20260418001343" },
];

// derive extra guessable attributes
KITS.forEach(k => {
  const clean = k.name.replace(/[^A-Za-z]/g, "");
  k.firstLetter = clean[0].toUpperCase();
  k.length = clean.length;
  k.words = k.name.trim().split(/\s+/).length;
});

if (typeof module !== "undefined") module.exports = KITS;
